// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnR_nzE8TGWyv7TEERtA8-cSejG1uK2Xw',
    appId: '1:782460885047:web:16d19281ab16b8bee247b2',
    messagingSenderId: '782460885047',
    projectId: 'pocketplan-dabe4',
    authDomain: 'pocketplan-dabe4.firebaseapp.com',
    storageBucket: 'pocketplan-dabe4.firebasestorage.app',
    measurementId: 'G-S0RXKET1ZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZbZpCdHALM7sbOJjBcBrTtMPWaaIKduE',
    appId: '1:782460885047:android:9acf5142366fed96e247b2',
    messagingSenderId: '782460885047',
    projectId: 'pocketplan-dabe4',
    storageBucket: 'pocketplan-dabe4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSZHZeJk531p76lZnwHpEswt61_w9raGI',
    appId: '1:782460885047:ios:3fc1f4732c9e2cf9e247b2',
    messagingSenderId: '782460885047',
    projectId: 'pocketplan-dabe4',
    storageBucket: 'pocketplan-dabe4.firebasestorage.app',
    iosClientId: '782460885047-h7t192ghmudlb9vkadafknnfqulvl3q8.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketPlan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSZHZeJk531p76lZnwHpEswt61_w9raGI',
    appId: '1:782460885047:ios:3fc1f4732c9e2cf9e247b2',
    messagingSenderId: '782460885047',
    projectId: 'pocketplan-dabe4',
    storageBucket: 'pocketplan-dabe4.firebasestorage.app',
    iosClientId: '782460885047-h7t192ghmudlb9vkadafknnfqulvl3q8.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketPlan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnR_nzE8TGWyv7TEERtA8-cSejG1uK2Xw',
    appId: '1:782460885047:web:1babf02c603a5c60e247b2',
    messagingSenderId: '782460885047',
    projectId: 'pocketplan-dabe4',
    authDomain: 'pocketplan-dabe4.firebaseapp.com',
    storageBucket: 'pocketplan-dabe4.firebasestorage.app',
    measurementId: 'G-R6E7XY1LWQ',
  );

}